### ISSUE TITLE
Problems using cxsd on Windows

### ISSUE THREAD

**Issue by patrickmeiring** [charto/cxsd#5]
Exporter.js uses a regex to replace path separators with forward slashes. On Windows, path.sep is a backslash, making the regex invalid as it is not escaped beforehand.

**Stack trace:**
Unhandled rejection SyntaxError: Invalid regular expression: /\/: \ at end of pattern
    at new RegExp (native)
    at JS.Exporter.getPathTo (C:\<removed>\cxsd\dist\schema\exporter\Exporter.js:48:72)
    at JS.Exporter.writeHeader (C:\<removed>\cxsd\dist\schema\exporter\Exporter.js:24:37)
    at JS.writeContents (C:\<removed>\cxsd\dist\schema\exporter\JS.js:211:17)
    at C:\<removed>\cxsd\dist\schema\exporter\Exporter.js:40:60
From previous event:
    at JS.Exporter.prepare (C:\<removed>\cxsd\dist\schema\exporter\Exporter.js:37:52)
    at JS.Transform.exec (C:\<removed>\cxsd\dist\schema\transform\Transform.js:38:38)
    at C:\<removed>\cxsd\dist\cli.js:52:62

**Comment by jjrv** [comment]
PR merged, thanks!

**Comment by maiermic** [comment]
@jjrv Please release this fix to npm. The current latest version `cxsd@0.1.0` still contains this bug.

**Comment by jjrv** [comment]
Sorry for the delay, it's released now.
